name: Deploy React App to GitHub Pages

on:
  push:
    branches: ["main"]  # Pokreće se na push prema "main" grani
  workflow_dispatch:  # Omogućava ručno pokretanje iz Actions tab-a

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ili verzija Node.js koju koristite

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Upload build folder
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          branch: gh-pages  # Grana gdje će se deployati
          folder: build  # Folder koji će biti deployan
